
data:
    name: lfw
    datapath: Datasets
    datatype: image
    url: http://vis-www.cs.umass.edu/lfw/lfw.tgz
    nclasses: 20
    height: 28
    width: 28
    channels: 3
    #labels: DEFAULT -> range(0,nclasses)

train:
  model: AlexNet
  modelpath:
  hyperparameters: 1,2,3,4


attack:
  model: ml_leaks
  modelpath:
  params:
  metrics:

